# Generated by cucumber-sinatra. (2013-05-07 14:20:35 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'capybara-webkit'
require 'rack'

# require 'rack/test'
# require 'rmagick'


# Capybara.app = JCA_Sinatra
Capybara.app = eval "Rack::Builder.new {( " + File.read(File.dirname(__FILE__) + '/../../config.ru') + "\n )}"
# Line above allows all the middleware to be loaded to capybara.

Capybara.javascript_driver = :webkit

class WarningSuppressor
  class << self
    def write(message)
      puts(message) unless message =~ /QFont::setPixelSize: Pixel size <= 0/
      0
    end
  end
end


Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app, stderr: WarningSuppressor)
end

class JCA_SinatraWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  JCA_SinatraWorld.new
  Rack::Builder.new do
    use Rack::Directory
    map '/pdfs/' do
      run Rack::Directory.new('./public/resources/pdfs')
    end
  end
end
