# Generated by cucumber-sinatra. (2013-05-07 14:20:35 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'capybara-webkit'
# require 'rack/test'
# require 'rmagick'

Capybara.app = JCA_Sinatra
Capybara.javascript_driver = :webkit
# Capybara.javascript_driver = :webkit_debug

# Culerity.jruby_invocation = File.expand_path("~/.rvm/bin/celerity_jruby")

class JCA_SinatraWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
  #Below to give me "get"
  # include Rack::Test::Methods
  # def app
  #   Rack::Directory.new('./public/resources/pdfs')
  # end
  
end

World do
  JCA_SinatraWorld.new
end
